In [19]:
import pandas as pd
import numpy as np
pokemon = pd.read_csv("pokemon.csv")

In [20]:
pokemon

#            Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1       Bulbasaur    Grass  Poison    318  45      49       49   
1      2         Ivysaur    Grass  Poison    405  60      62       63   
2      3        Venusaur    Grass  Poison    525  80      82       83   
3      3   Mega Venusaur    Grass  Poison    625  80     100      123   
4      4      Charmander     Fire     NaN    309  39      52       43   
..   ...             ...      ...     ...    ...  ..     ...      ...   
795  719         Diancie     Rock   Fairy    600  50     100      150   
796  719    Mega Diancie     Rock   Fairy    700  50     160      110   
797  720  Hoopa Confined  Psychic   Ghost    600  80     110       60   
798  720   Hoopa Unbound  Psychic    Dark    680  80     160       60   
799  721       Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 13 columns]

In [21]:
pokemon.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [22]:
df = pd.DataFrame()
df[["Type 1", "Type 2", "Attack", "Defense", "Speed", "Name"]]= pokemon.loc[:, ["Type 1", "Type 2", "Attack", "Defense", "Speed", "Name"]]

In [23]:
df

Type 1  Type 2  Attack  Defense  Speed            Name
0      Grass  Poison      49       49     45       Bulbasaur
1      Grass  Poison      62       63     60         Ivysaur
2      Grass  Poison      82       83     80        Venusaur
3      Grass  Poison     100      123     80   Mega Venusaur
4       Fire     NaN      52       43     65      Charmander
..       ...     ...     ...      ...    ...             ...
795     Rock   Fairy     100      150     50         Diancie
796     Rock   Fairy     160      110    110    Mega Diancie
797  Psychic   Ghost     110       60     70  Hoopa Confined
798  Psychic    Dark     160       60     80   Hoopa Unbound
799     Fire   Water     110      120     70       Volcanion

[800 rows x 6 columns]

In [24]:
#replacing np.nan with 'No Secondary Type'
df["Type 2"] = df["Type 2"].replace(np.nan, "No Secondary Type")

In [25]:
df

Type 1             Type 2  Attack  Defense  Speed            Name
0      Grass             Poison      49       49     45       Bulbasaur
1      Grass             Poison      62       63     60         Ivysaur
2      Grass             Poison      82       83     80        Venusaur
3      Grass             Poison     100      123     80   Mega Venusaur
4       Fire  No Secondary Type      52       43     65      Charmander
..       ...                ...     ...      ...    ...             ...
795     Rock              Fairy     100      150     50         Diancie
796     Rock              Fairy     160      110    110    Mega Diancie
797  Psychic              Ghost     110       60     70  Hoopa Confined
798  Psychic               Dark     160       60     80   Hoopa Unbound
799     Fire              Water     110      120     70       Volcanion

[800 rows x 6 columns]

In [26]:
#Scaling Attack, Defense, Speed
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
df.iloc[:, 2:-1] = mm.fit_transform(df.iloc[:, 2:-1])
df.iloc[:,2:-1] = df.iloc[:,2:-1].applymap(lambda x:x*100)

In [27]:
#creating fake data...
import random
import math
def temp_func(x):
    opt = random.choice([0,1,2,3])
    if opt == 0:
        #floor operation
        x = math.floor(x)
    elif opt == 1:
        #ceil operation
        x = math.ceil(x)
    elif opt == 2:
        #add some value
        x = x + random.choice([1,2,3,4,5,6])
    else:
        #subtract some value
        x = x - random.choice([1,2,3,4,5,6])
    return x

temp_df = df.copy()
temp_df.iloc[:,2:-1] = temp_df.iloc[:,2:-1].applymap(temp_func)

temp_df2 = df.copy()
temp_df2.iloc[:,2:-1] = temp_df2.iloc[:,2:-1].applymap(temp_func)

temp_df3 = df.copy()
temp_df3.iloc[:,2:-1] = temp_df3.iloc[:,2:-1].applymap(temp_func)

temp_df4 = df.copy()
temp_df4.iloc[:,2:-1] = temp_df4.iloc[:,2:-1].applymap(temp_func)


In [28]:
df = pd.concat([df, temp_df, temp_df2, temp_df3])
df

Type 1             Type 2     Attack    Defense      Speed  \
0      Grass             Poison  23.783784  19.555556  22.857143   
1      Grass             Poison  30.810811  25.777778  31.428571   
2      Grass             Poison  41.621622  34.666667  42.857143   
3      Grass             Poison  51.351351  52.444444  42.857143   
4       Fire  No Secondary Type  25.405405  16.888889  34.285714   
..       ...                ...        ...        ...        ...   
795     Rock              Fairy  47.351351  61.444444  28.714286   
796     Rock              Fairy  79.783784  47.000000  60.000000   
797  Psychic              Ghost  56.000000  25.000000  35.142857   
798  Psychic               Dark  83.000000  24.000000  43.000000   
799     Fire              Water  52.756757  52.000000  37.000000   

               Name  
0         Bulbasaur  
1           Ivysaur  
2          Venusaur  
3     Mega Venusaur  
4        Charmander  
..              ...  
795         Diancie  
796    Mega Diancie  
797  Hoopa Confined  
798   Hoopa Unbound  
799       Volcanion  

[3200 rows x 6 columns]

In [29]:
#X -> Independent variables
#y -> Dependent variable
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [30]:
#Encoding Categorical data: Type 1, Type 2
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder1', OneHotEncoder(sparse = False ), [0,1])], remainder = "passthrough" )
X = np.array(ct.fit_transform(X))

In [31]:
#Encoding Categorical data: Name
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y)
y = le.transform(y)

In [32]:
print(X)

[[0.0 0.0 0.0 ... 23.783783783783786 19.555555555555554
  22.857142857142854]
 [0.0 0.0 0.0 ... 30.810810810810814 25.777777777777782
  31.428571428571427]
 [0.0 0.0 0.0 ... 41.62162162162162 34.66666666666667 42.857142857142854]
 ...
 [0.0 0.0 0.0 ... 56.0 25.0 35.142857142857146]
 [0.0 0.0 0.0 ... 83.0 24.0 43.0]
 [0.0 0.0 0.0 ... 52.75675675675676 52.0 37.0]]


In [33]:
print(y)

[ 68 304 746 ... 290 291 756]


In [34]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X, y)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [35]:
#testing with random values...
X_test = temp_df4.iloc[:,:-1].values
y_test = temp_df4.iloc[:,-1].values
X_test = np.array(ct.transform(X_test))
y_test = le.transform(y_test)

In [36]:
from sklearn.metrics import accuracy_score
y_pred = classifier.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.815
